name: Daily Notifications

on:
  schedule:
    - cron: '0 * * * *'  # 8:00 AM UTC every day
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Notifications
        run: |
          curl -G "${{ secrets.VERCEL_CRON_URL }}" \
            --data-urlencode "secret=${{ secrets.CRON_SECRET }}"